# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=30)),
                ('weekday', models.CharField(default=b'', max_length=30)),
                ('menu', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
