# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(default='', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('menu', models.CharField(default='', max_length=100)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
